# Generated by Django 5.2.1 on 2025-06-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('used_space_gb', models.FloatField(default=1.2)),
                ('total_space_gb', models.FloatField(default=5.0)),
                ('documents_mb', models.FloatField(default=450.0)),
                ('videos_mb', models.FloatField(default=650.0)),
                ('images_mb', models.FloatField(default=80.0)),
                ('code_mb', models.FloatField(default=20.0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='EMSI Share', max_length=100)),
                ('logo', models.TextField(blank=True, null=True)),
                ('resources_per_page', models.IntegerField(default=20)),
                ('forum_posts_per_page', models.IntegerField(default=15)),
                ('events_per_page', models.IntegerField(default=10)),
                ('users_per_page', models.IntegerField(default=25)),
                ('enable_registration', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('public_profiles', models.BooleanField(default=True)),
                ('password_policy', models.BooleanField(default=True)),
                ('session_timeout', models.BooleanField(default=True)),
            ],
        ),
    ]
