# Generated by Django 5.2.1 on 2025-05-31 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='eventfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='eventreminder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventreminder',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventreminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventresource',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventresource',
            name='uploaded_by',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_datetime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='online_link',
            new_name='meeting_link',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_datetime',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('workshop', 'Workshop'), ('exam', 'Exam'), ('deadline', 'Deadline'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('maybe', 'Maybe'), ('declined', 'Declined')], default='attending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='EventAttendance',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.DeleteModel(
            name='EventFeedback',
        ),
        migrations.DeleteModel(
            name='EventReminder',
        ),
        migrations.DeleteModel(
            name='EventResource',
        ),
    ]
