# Generated by Django 5.2.1 on 2025-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
