# Generated by Django 5.0 on 2025-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcollaborator_event_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('workshop', 'Workshop'), ('exam', 'Exam'), ('deadline', 'Deadline'), ('meeting', 'Meeting'), ('other', 'Other'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('project', 'Project'), ('social', 'Social Event'), ('competition', 'Competition'), ('training', 'Training')], default='other', max_length=20),
        ),
    ]
