# Generated by Django 4.2.7 on 2025-05-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiztag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quiztag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiztag',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='allow_review',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_results_immediately',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='shuffle_options',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='shuffle_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='quizresource',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='quizresource',
            name='is_downloadable',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=15),
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
        migrations.DeleteModel(
            name='QuizTag',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='earned_points',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user_agent',
        ),
    ]
