# Generated by Django 5.2.1 on 2025-06-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiztag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
