# Generated by Django 4.2.7 on 2025-05-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='resourcecomment',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcecomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='resourcerating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resourcerating',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcerating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='visibility',
        ),
        migrations.DeleteModel(
            name='ResourceAccess',
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
        migrations.DeleteModel(
            name='ResourceComment',
        ),
        migrations.DeleteModel(
            name='ResourceRating',
        ),
    ]
