# Generated by Django 4.2.7 on 2025-05-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('resources', '0002_remove_resourcecomment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='rooms.room'),
        ),
    ]
