# Generated by Django 5.2.1 on 2025-05-31 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_resource_file_resource_file_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('code', 'Code'), ('pdf', 'PDF Document'), ('audio', 'Audio'), ('image', 'Image'), ('doc', 'Word Document'), ('ppt', 'PowerPoint'), ('excel', 'Excel'), ('zip', 'ZIP Archive'), ('link', 'External Link'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory'),
        ),
    ]
