# Generated by Django 5.0 on 2025-06-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_resource_approval_fields'),
        ('resources', '0008_resource_is_classwork_studentanswer'),
    ]

    operations = [
    ]
