# Generated by Django 5.0 on 2025-06-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_merge_20250603_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_classwork',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
