// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oskhpqketxbegocxrdzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9za2hwcWtldHhiZWdvY3hyZHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTk2OTQsImV4cCI6MjA2MDg5NTY5NH0.3-VzRQ2lj_ufbkrupIMbuUIITs5UMRFOljRKYx_u5_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);