# Generated by Django 5.2.1 on 2025-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_date_of_birth_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
